repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --in-place]
  - repo: local
    hooks:
      - id: pytest-check-all
        name: pytest-check-all
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
        stages:
          - pre-push
      - id: pytest-check-without-integration
        name: pytest-check-without-integration
        entry: poetry run pytest --ignore-glob=*integration_test.py
        language: system
        pass_filenames: false
        always_run: true
        stages:
          - pre-commit