site_name: gapper API Reference
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true