site_name: gapper API Reference
site_description: The API Reference for gapper module, a Python autograder generator for Gradescope.
repo_url: https://github.com/FlickerSoul/gapper
site_dir: site
docs_dir: docs
copyright: Copyright &copy; 2023 Larry Zeng and Contributors

nav:
  - Home: index.md
  - Tutorials:
      - Tutorials/Getting-Started.md
      - Tutorials/Detailed-Usage.md
      - Tutorials/gap_-Keywords.md
      - Tutorials/Test-Result-(Proxy).md
  - API:
    - API/problem.md
    - API/test_cases.md
    - API/test_result.md
    - API/utils.md
    - API/pipeline_support.md
    - API/test_case_wrapper.md
    - API/result_synthesizer.md
    - API/tester.md
    - API/gradescope_data_types.md
    - API/errors.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FlickerSoul/gapper
    - icon: fontawesome/brands/telegram
      link: https://t.me/the_universe_observer

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.top
    - navigation.tabs
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.footer
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - css/api-styling.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: sphinx
            separate_signature: true
            show_signature_annotations: true
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.superfences