[tool.poetry]
name = "gap"
version = "0.1.0"
description = "Gradescope Assignment Packer"
authors = ["Heyuan Zeng <hi@universe.observer>"]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
gap = "gap.cli:app"
gradescope-assignment-packer = "gap.cli:app"

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.9.0"
dill = "^0.3.7"
pytest-mock = "^3.11.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
